# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.3
  cypress: cypress-io/cypress@1.28.0

ref:
  container: &container
    docker:
      - image: node:12.22.0
    working_directory: ~/repo

executors:
  with-chrome-and-firefox:
    docker:
      - image: 'cypress/browsers:node12.19.0-chrome86-ff82'
    resource_class: medium+

commands:
  install-packages:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-path: |
            ~/.yarn
            ~/.cache/Cypress
            node_modules

jobs:
  lint:
    <<: *container
    steps:
      - checkout
      - install-packages
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *container
    steps:
      - checkout
      - install-packages
      - run:
          name: Lint
          command: yarn build

workflows:
  build-and-test:
    jobs:
      - lint
      - build
      - cypress/run:
          name: E2E
          browser: chrome
          executor: with-chrome-and-firefox
          wait-on: 'http://localhost:3000'
          yarn: true
          start: yarn playground:start
          record: true
          ci-build-id: ${CIRCLE_SHA1:0:8}
