# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.1.0
  cypress: cypress-io/cypress@3.3.1

ref:
  container: &container
    docker:
      - image: node:20.5
    working_directory: ~/repo

executors:
  with-chrome-and-firefox:
    docker:
      - image: 'cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1'

commands:
  install-packages:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-path: |
            ~/.yarn
            ~/.cache/Cypress
            node_modules

workflows:
  e2e:
    jobs:
      - cypress/run:
          name: 'test-e2e'
          package-manager: yarn
          cypress-command: npx start-test serve 8090 'npx cypress run --record --parallel'
          start-command: yarn playground:e2e && yarn serve
          post-steps:
            - store_artifacts:
                path: coverage
            - store_test_results:
                path: cypress/results
            - codecov/upload:
                file: 'coverage/clover.xml'
                flags: integration
